{{- if .Values.configMaps }}
{{- range .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
data:
{{ .data | indent 2 }}
...
{{- end }}
{{- end }}
